### ISSUE TITLE
Unnessary type converting

### ISSUE THREAD

**Issue by 18001767679** [Sombrero64/PythonSharp#5]
**Describe the bug**
There are some unnessary type converting in the source code.

**Expected behavior**
Only do type converting when needed;otherwise,it will need more time to run your functions.

 **Screenshots**
no
**Desktop (please complete the following information):**
Nah,its the source code(not related to desktop)

**Smartphone (please complete the following information):**
Nah,its the source code(not related to smartphone)

**Additional context**
Please remove the unnessary type converting in the source code.

**Comment by Sombrero64** [comment]
Thank you for your response. I will take care of this.
